# Generated by Django 5.2.12 on 2026-03-09 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_reservationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
