# Generated by Django 5.2.12 on 2026-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0004_reservation_qr_token_alter_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled')], default='available', max_length=20),
        ),
    ]
