# Generated by Django 5.2.12 on 2026-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0005_alter_locker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlog',
            name='action',
            field=models.CharField(choices=[('reserve', 'Reserve'), ('cancel', 'Cancel'), ('maintenance', 'Maintenance'), ('reopen', 'Reopen'), ('disable', 'Disable')], max_length=20),
        ),
    ]
