# Generated by Django 5.2.12 on 2026-04-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_alter_reservationlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlog',
            name='action',
            field=models.CharField(choices=[('reserve', 'Reserve'), ('cancel', 'Cancel'), ('maintenance', 'Maintenance'), ('reopen', 'Reopen'), ('disable', 'Disable'), ('qr_verify', 'QR Verify')], max_length=20),
        ),
    ]
