# Generated by Django 5.2.12 on 2026-04-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0007_alter_reservationlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_state', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('lock_state', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_action', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('locker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locker.locker')),
            ],
        ),
    ]
