# Generated by Django 5.2.12 on 2026-04-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0008_lockerdevicestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlog',
            name='action',
            field=models.CharField(choices=[('reserve', 'Reserve'), ('cancel', 'Cancel'), ('maintenance', 'Maintenance'), ('reopen', 'Reopen'), ('disable', 'Disable'), ('qr_verify', 'QR Verify'), ('unlock_result', 'Unlock Result')], max_length=20),
        ),
    ]
