# Generated by Django 5.2.12 on 2026-04-12 16:00

import locker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0009_alter_reservationlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pin_code',
            field=models.CharField(default=locker.models.generate_pin, max_length=6),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled'), ('pin_verify', 'PIN Verify')], default='available', max_length=20),
        ),
    ]
