# Generated by Django 5.2.12 on 2026-04-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0010_reservation_pin_code_alter_locker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='access_token',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationlog',
            name='action',
            field=models.CharField(choices=[('reserve', 'Reserve'), ('cancel', 'Cancel'), ('maintenance', 'Maintenance'), ('reopen', 'Reopen'), ('disable', 'Disable'), ('qr_verify', 'QR Verify'), ('unlock_result', 'Unlock Result'), ('pin_verify', 'PIN Verify')], max_length=20),
        ),
    ]
